### ISSUE TITLE
Err: Invalid access of discarded(invalid, deleted) uWS.HttpResponse/SSLHttpResponse

### ISSUE THREAD

**Issue by RayNCooper** [TheEngineerhub/staticit#1]
Hey there,

first of all I would like to compliment you for having thought of this workaround that eases integrating pre-rendered static sites in frontend frameworks.

Stack: 
- Vue 3 + Vite (Scaffolded using Vite CLI) 
- Node 16
- M1 Macbook Air 2020

Now onto the issue: I am trying to static-ify a bunch of routes in my frontend project.
But sadly there is this following error that appears in 80% of cases:

<img width="887" alt="image" src="https://user-images.githubusercontent.com/39743711/172067324-0c05eea8-9cfc-4fe8-9f71-61610a61ff11.png">

The special thing about this is, that it works some of the time. Most of the time it does not.

Cheers and keep up the good work!

**Comment by Alcadramin** [comment]
Hello! - Sorry for late response.

Congratz on the first issue of this project haha 😄 Seem's like this is related with uWebsockets - sifrr and found some issues with the error message u've provided. 

- https://github.com/sifrr/sifrr/issues/381
- https://github.com/uNetworking/uWebSockets.js/discussions/123

I'm kind of aware of the stability (and maintainability) issues of sifrr which I choose it because of the speed advantage, however it gave me headaches on my arm machine as well. I will switch the backend to well known express.js.

Thank you.

**Comment by Alcadramin** [comment]
Hi @RayNCooper,

Issue should be resolved, please upgrade the package to `^1.2.1`.

**Comment by RayNCooper** [comment]
Great work! Thanks a million.
